import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";

import "./globals.css";
import { GlobalUIProvider } from "@/app/context/GlobalUIContext";
import { NameAndLocateProvider } from "./context/NameAndLocateContext";
import { LoadingProvider } from "./context/LoadingContext";
import { ImageProvider } from "./context/ImageContext";
import { ThankYouProvider } from "./context/ThankYouContext";
import { CategoryProvider } from "./context/CategoryContext";
import { PictureDataProvider } from "./context/PictureDataContext";
import { ChosenStatProvider } from "./context/ChosenStatContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roobert",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <ChosenStatProvider>
          <PictureDataProvider>
            <CategoryProvider>
              <ThankYouProvider>
                <ImageProvider>
                  <LoadingProvider>
                    <NameAndLocateProvider>
                      <GlobalUIProvider>{children}</GlobalUIProvider>
                    </NameAndLocateProvider>
                  </LoadingProvider>
                </ImageProvider>
              </ThankYouProvider>
            </CategoryProvider>
          </PictureDataProvider>
        </ChosenStatProvider>
      </body>
    </html>
  );
}
